Check download comments after parsing args

diff --git a/ktlint-install b/ktlint-install
--- a/ktlint-install
+++ b/ktlint-install
@@ -40,33 +40,6 @@ try_as_root() {
 	fi
 }
 
-# region check download commands
-
-wget_available=$(if command_exists wget; then echo true; else echo false; fi)
-readonly wget_available
-
-curl_available=$(if command_exists curl; then echo true; else echo false; fi)
-readonly curl_available
-
-case $wget_available,$curl_available in
-	('true,'*) # preferring `wget` over `curl` for no particular reason
-		download_file() {
-			wget -O "$2" -- "$1"
-		}
-		;;
-	(*',true')
-		download_file() {
-			curl -o "$2" -- "$1"
-		}
-		;;
-	('false,false')
-		echo "$(argv0): wget or curl missing" >&2
-		exit 48
-		;;
-esac
-
-# endregion
-
 # region args
 
 case $# in
@@ -105,6 +78,33 @@ if ! printf '%s' "$requested_version" | grep -Eq '^[[:digit:]]+\.[[:digit:]]+\.[
 
 	unset -v ans
 fi
+
+# endregion
+
+# region check download commands
+
+wget_available=$(if command_exists wget; then echo true; else echo false; fi)
+readonly wget_available
+
+curl_available=$(if command_exists curl; then echo true; else echo false; fi)
+readonly curl_available
+
+case $wget_available,$curl_available in
+	('true,'*) # preferring `wget` over `curl` for no particular reason
+		download_file() {
+			wget -O "$2" -- "$1"
+		}
+		;;
+	(*',true')
+		download_file() {
+			curl -o "$2" -- "$1"
+		}
+		;;
+	('false,false')
+		echo "$(argv0): wget or curl missing" >&2
+		exit 48
+		;;
+esac
 
 # endregion
 
